version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sportpartner_kereso
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "8081:8081"
    networks:
      - mysql-network
    depends_on:
      - mysql
      - frontend 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    container_name: frontend-container
    ports:
      - "3000:3000"
    networks:
      - mysql-network
    depends_on:
      - mysql  
volumes:
  mysql-data:
networks:
  mysql-network:
    driver: bridge